import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { Smooch_Sans } from "next/font/google";
import "./globals.css";
import Topbar from "@/components/Topbar";
import { Metrophobic } from "next/font/google";

const metrophobic = Metrophobic({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-metrophobic",
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});
const smoochSans = Smooch_Sans({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  variable: "--font-smooch-sans",
});

export const metadata: Metadata = {
  title: "Shikayat",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={metrophobic.variable}>
      <head>
        <link
          rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css"
        />
      </head>
      <body className={`font-metrophobic antialiased`}>{children}</body>
    </html>
  );
}
